<a href="https://colab.research.google.com/github/32173313/Data_Science/blob/main/Week2_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[4, 5, 6], [7, 8, 9]])

print("A:\n", A)
print("B:\n", B)

vstacked = np.vstack((A, B))
hstacked = np.hstack((A, B))

print("vstacked:\n", vstacked)
print("hstacked:\n", hstacked)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[4 5 6]
 [7 8 9]]
vstacked:
 [[1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]]
hstacked:
 [[1 2 3 4 5 6]
 [4 5 6 7 8 9]]


In [3]:
common_elements = np.intersect1d(A, B)
print("Common elements:\n", common_elements)

Common elements:
 [4 5 6]


In [4]:
idx = np.where((A >= 5) & (A <= 10))
filtered_A = A[idx]
print("\nNumbers in A between 5 and 10:", filtered_A)


Numbers in A between 5 and 10: [5 6]


In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

indices = np.where((iris_2d[:, 0] < 5.0) & (iris_2d[:, 2] > 1.5))
filtered = iris_2d[indices]
print(filtered)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]

print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [8]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
row_sum = df.sum(axis=1)
filtered = df[row_sum > 100]
print(filtered)

     0   1   2   3
1   37  23  33  18
2   31  34  29  36
4   38  34  12  32
8   17  37  19  32
10  37  29  35  30
11  18  36  25  38
